### ISSUE TITLE
Find-XKCD function

### ISSUE THREAD

**Issue by markwragg** [markwragg/Powershell-XKCD#2]
Build an offline cache of all comic data which we can then search to find specific comics based on keyword, date etc.

**Comment by markwragg** [comment]
Is find the approved verb?

**Comment by martin9700** [comment]
It is.

**Comment by markwragg** [comment]
Finally implemented this cmdlet :). It works via a cache of the API data stored in the module directory, and a pre-created cache comes with the module with the comics up to today. The cmdlet will automatically append new comics to the cache if it finds its behind and that should take minimal time.
